name: TinyTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install TinyTeX
      run:  bash .github/workflows/install-TinyTeX_hithesis.sh
    - name: Test thesis
      run: |
        export PATH="$HOME/bin:$PATH";
        which latex
        which splitindex
        make thesis
    - name: Test doc
      run: |
        export PATH="$HOME/bin:$PATH";
        make doc
