name: MacTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Install MacTeX
      run:  |
        brew cask install basictex

        export PATH="/Library/TeX/texbin:$PATH"

        sudo tlmgr install l3build \
          fontname fontspec xetex \
          cjk environ ms trimspaces ulem zhnumber \
          fandol tex-gyre xits \
          bibunits caption enumitem etoolbox footmisc notoccite pdfpages unicode-math \
          booktabs koma-script nomencl ntheorem siunitx xkeyval \
          pdflscape \
          hologo listings xcolor \
          diagbox float fp metalogo multirow pict2e \
          latexmk ctex ntheorem newtx fontaxes pdfpages enumitem environ trimspaces\
          footmisc varwidth changepage placeins multirow subfigure ccaption splitindex\
          xltxtra realscripts siunitx jknapltx algorithm2e ifoddpage relsize\
          listings glossaries mfirstuc textcase xfor datatool tracklang pdflscape rsfs\
          txfonts xecjk tex-gyre newpx

        cd $HOME/Library/Fonts
        curl -O https://github.com/StellarCN/scp_zh/raw/master/fonts/SimSun.ttf
        curl -O https://github.com/StellarCN/scp_zh/raw/master/fonts/SimHei.ttf
        curl -O https://github.com/Halfish/lstm-ctc-ocr/raw/master/fonts/simkai.ttf
        curl -O https://github.com/Halfish/lstm-ctc-ocr/raw/master/fonts/simfang.ttf
        curl -O https://github.com/dangxinchudian/interfacedbcms/raw/master/tcpdf/msyh.ttf
        curl -O https://github.com/owent-utils/font/raw/master/%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91/MSYH.TTC
        curl -O https://github.com/owent-utils/font/raw/master/%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91/MSYHBD.TTC
        curl -O https://github.com/junmer/source-han-serif-ttf/raw/master/SubsetTTF/CN/SourceHanSerifCN-Regular.ttf

    - name: Test thesis
      run: |
        export PATH="/Library/TeX/texbin:$PATH"
        make thesis
    - name: Test doc
      run: |
        export PATH="/Library/TeX/texbin:$PATH"
        make doc
