name: Win_MiKTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install MiKTeX
      run: |
        wget https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-2.9.6942_2-x64.zip
        unzip miktexsetup-2.9.6942_2-x64.zip
        miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=basic download
        miktexsetup install

    - name: Test thesis
      run: |
        make thesis
    - name: Test doc
      run: |
        export PATH="/usr/local/bin:$PATH";
        make doc
