name: MacTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:

    - name: Install MacTeX
      run:  bash .github/workflows/install-texlive.sh
    - name: Test thesis
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make thesis
    - name: Test doc
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make doc
