name: MacTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      run:  actions/checkout@v1

    - name: Install MacTeX
      run:  |
        brew cast install mactex
        cd $HOME/Library/Fonts
        curl -O https://github.com/StellarCN/scp_zh/raw/master/fonts/SimSun.ttf
        curl -O https://github.com/StellarCN/scp_zh/raw/master/fonts/SimHei.ttf
        curl -O https://github.com/Halfish/lstm-ctc-ocr/raw/master/fonts/simkai.ttf
        curl -O https://github.com/Halfish/lstm-ctc-ocr/raw/master/fonts/simfang.ttf
        curl -O https://github.com/dangxinchudian/interfacedbcms/raw/master/tcpdf/msyh.ttf
        curl -O https://github.com/owent-utils/font/raw/master/%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91/MSYH.TTC
        curl -O https://github.com/owent-utils/font/raw/master/%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91/MSYHBD.TTC
        curl -O https://github.com/junmer/source-han-serif-ttf/raw/master/SubsetTTF/CN/SourceHanSerifCN-Regular.ttf

    - name: Test thesis
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make thesis
    - name: Test doc
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        make doc
